/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef __ASM_CHERI_H
#define __ASM_CHERI_H

#define CHERI_PERMS_READ \
	(CHERI_BW_PERM_READ | CHERI_BW_PERM_CAP)

#define CHERI_PERMS_WRITE \
	(CHERI_BW_PERM_WRITE | CHERI_BW_PERM_CAP)

#define CHERI_PERMS_EXEC \
	(CHERI_BW_PERM_EXECUTE | CHERI_BW_PERM_SYSTEM_REGS)

#define CHERI_PERMS_ROOTCAP \
	(CHERI_PERM_SW_VMEM)

#define CHERI_PERM_GLOBAL 0
#define CHERI_PERM_LOAD CHERI_BW_PERM_READ
#define CHERI_PERM_STORE CHERI_BW_PERM_WRITE
#define CHERI_PERM_EXECUTE CHERI_BW_PERM_EXECUTE

#define CHERI_PERMS_MIN_CODE (CHERI_BW_PERM_READ | CHERI_BW_PERM_EXECUTE)

#endif /* __ASM_CHERI_H */
