/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef __ASM_CHERI_H
#define __ASM_CHERI_H

#define CHERI_PERMS_READ \
	(CHERI_BW_PERM_READ | CHERI_BW_PERM_CAP)

#define CHERI_PERMS_WRITE \
	(CHERI_BW_PERM_WRITE | CHERI_BW_PERM_CAP)

#define CHERI_PERMS_EXEC \
	(CHERI_BW_PERM_EXECUTE | CHERI_BW_PERM_SYSTEM_REGS)

#define CHERI_PERMS_ROOTCAP \
	(CHERI_PERM_SW_VMEM)

#endif /* __ASM_CHERI_H */
