# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_CODASIP) += a730-mp1-hobgoblin-genesys2.dtb
dtb-$(CONFIG_ARCH_CODASIP) += a730-mp1-hobgoblin-genesys2-etherlite.dtb
dtb-$(CONFIG_ARCH_CODASIP) += a730-mp1-hobgoblin-genesys2-qemu.dtb
