# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_CODASIP) += a70x-hobgoblin-qemu.dtb
dtb-$(CONFIG_ARCH_CODASIP) += a70x-hobgoblin-etherlite.dtb
dtb-$(CONFIG_ARCH_CODASIP) += a70x-hobgoblin-axi-emac.dtb
